# Generated by Django 6.0.5 on 2026-05-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150)),
                (
                    "location",
                    models.CharField(
                        help_text="e.g., Toronto, ON or Remote", max_length=100
                    ),
                ),
                ("job_title", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if currently working here",
                        null=True,
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "summary",
                    models.TextField(
                        help_text="Core team responsibilities, data architectures, and high-level achievements"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("TAX", "Tax Filing"),
                            ("RESUME", "Resume & LinkedIn Optimization"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price in CAD", max_digits=6
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="e.g., Python, PySpark, Databricks, AWS, Django",
                        max_length=200,
                    ),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
                ("live_demo_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "associated_experience",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link this project to a specific employer, or leave blank if it is an independent side-project",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="portfolio.experience",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
