# Generated by Django 6.0.5 on 2026-05-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_contactmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("WEBSITE", "Personal/Business Web Services"),
                    ("TAX", "Tax Filing"),
                    ("RESUME", "Resume Optimization"),
                    ("LINKEDIN", "LinkedIn Optimization"),
                ],
                max_length=10,
            ),
        ),
    ]
