# Generated by Django 6.0.5 on 2026-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_service_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("WEBSITE", "Personal/Business Web Services"),
                    ("GRAPHIC DESIGN", "Graphic Design"),
                    ("LOGO DESIGN", "Logo Design"),
                    ("TAX", "Tax Filing"),
                    ("RESUME", "Resume Optimization"),
                    ("LINKEDIN", "LinkedIn Optimization"),
                ],
                max_length=20,
            ),
        ),
    ]
